-- Schema para Oracle Database (OCI)

CREATE TABLE perfis (
    id_perfil NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR2(255) NOT NULL,
    status NUMBER DEFAULT 1
);

CREATE TABLE permissoes (
    id_permissao NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR2(255) NOT NULL
);

CREATE TABLE perfil_permissao (
    id_perfil NUMBER,
    id_permissao NUMBER,
    CONSTRAINT fk_pp_perfil FOREIGN KEY (id_perfil) REFERENCES perfis(id_perfil),
    CONSTRAINT fk_pp_permissao FOREIGN KEY (id_permissao) REFERENCES permissoes(id_permissao)
);

CREATE TABLE usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(255) NOT NULL,
    login VARCHAR2(255) NOT NULL UNIQUE,
    senha_hash VARCHAR2(255) NOT NULL,
    id_perfil NUMBER,
    status NUMBER DEFAULT 1,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_usu_perfil FOREIGN KEY (id_perfil) REFERENCES perfis(id_perfil)
);

CREATE TABLE dizimistas (
    id_dizimista NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(255) NOT NULL,
    cpf VARCHAR2(14) UNIQUE,
    telefone VARCHAR2(20),
    email VARCHAR2(255),
    endereco VARCHAR2(255),
    bairro VARCHAR2(100),
    cidade VARCHAR2(100),
    cep VARCHAR2(20),
    data_ingresso TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_nascimento DATE,
    status NUMBER DEFAULT 1,
    observacoes CLOB
);

CREATE TABLE missas (
    id_missa NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_missa VARCHAR2(20) NOT NULL,
    hora VARCHAR2(10) NOT NULL,
    comunidade VARCHAR2(200),
    celebrante VARCHAR2(200),
    tipo VARCHAR2(100),
    status NUMBER DEFAULT 1
);

CREATE TABLE tipos_pagamento (
    id_tipo_pagamento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR2(100) NOT NULL,
    status NUMBER DEFAULT 1
);

CREATE TABLE recebimentos (
    id_recebimento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_recebimento TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    competencia VARCHAR2(10) NOT NULL,
    id_dizimista NUMBER NOT NULL,
    valor NUMBER(10,2) NOT NULL,
    id_tipo_pagamento NUMBER NOT NULL,
    id_missa NUMBER,
    id_usuario NUMBER NOT NULL,
    status NUMBER DEFAULT 1,
    observacao VARCHAR2(1000),
    CONSTRAINT fk_rec_diz FOREIGN KEY (id_dizimista) REFERENCES dizimistas(id_dizimista),
    CONSTRAINT fk_rec_tipo FOREIGN KEY (id_tipo_pagamento) REFERENCES tipos_pagamento(id_tipo_pagamento),
    CONSTRAINT fk_rec_missa FOREIGN KEY (id_missa) REFERENCES missas(id_missa),
    CONSTRAINT fk_rec_usu FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
);

CREATE TABLE auditoria (
    id_auditoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabela VARCHAR2(100) NOT NULL,
    id_registro NUMBER NOT NULL,
    operacao VARCHAR2(50) NOT NULL,
    usuario VARCHAR2(100) NOT NULL,
    data_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dados_anteriores CLOB,
    dados_novos CLOB
);
